spring:
  application:
    name: image-ai-perplexity

  ai:
    openai:
      api-key: ${PERPLEXITY_API_KEY}
      base-url: https://api.perplexity.ai
      chat:
        completions-path: /chat/completions
        options:
          model: sonar-pro
          temperature: 0.7
          max-tokens: 2048
          response-format:
            type: json_schema
            json_schema:
              type: object
              properties:
                description:
                  type: [string, "null"]
                analysis:
                  type: [string, "null"]
                detectedElements:
                  type: [string, "null"]
                colors:
                  type: [string, "null"]
                composition:
                  type: [string, "null"]
                quality:
                  type: [string, "null"]
                contextualInfo:
                  type: [string, "null"]
                additionalDetails:
                  type: [string, "null"]
              required: []
      embedding:
        enabled: false
server:
  port: 8080
logging:
  level:
    org.springframework.ai: DEBUG
